name: QMK Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  qmk_build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git make gcc unzip
        pip3 install qmk

    - name: Inicializar entorno QMK
      run: |
        qmk setup -y
        qmk doctor

    - name: Compilar teclado desde build.yaml
      run: |
        qmk compile --build-yaml build.yaml
