name: QMK Build

on:
  push:
    branches: [main]  # ← Cambia si usas otra rama
  pull_request:
  workflow_dispatch:  # Permite ejecución manual desde la pestaña Actions

jobs:
  qmk_build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Instalar dependencias
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip git make gcc unzip
        pip3 install qmk

    - name: Inicializar entorno QMK
      run: |
        qmk setup -y --home ${{ github.workspace }}/qmk_firmware
        cd qmk_firmware
        qmk doctor

    - name: Copiar build.yaml
      run: cp ../build.yaml .

    - name: Compilar teclado desde build.yaml
      run: |
        cd qmk_firmware
        qmk compile --build-yaml build.yaml
