name: QMK Build

on:
  push:
    branches: [master]  # Change if you use a different default branch
  pull_request:
  workflow_dispatch:  # Allows manual execution from the Actions tab

jobs:
  qmk_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip git make gcc unzip
          pip3 install --upgrade qmk

      - name: Setup QMK Firmware environment
        run: |
          if [ ! -d "qmk_firmware" ]; then
            qmk setup -y --home "$GITHUB_WORKSPACE/qmk_firmware"
          fi
          cd qmk_firmware
          qmk doctor

      - name: Copy build.yaml to QMK folder
        run: |
          cp "$GITHUB_WORKSPACE/build.yaml" "$GITHUB_WORKSPACE/qmk_firmware/"

      - name: Compile keyboard from build.yaml
        run: |
          cd qmk_firmware
          qmk compile --build-yaml build.yaml

      - name: Upload firmware artifacts
        if: success()  # Only run if previous steps succeeded
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            qmk_firmware/*.hex
            qmk_firmware/*.bin
            qmk_firmware/*.uf2
